### ISSUE TITLE
V1.6.6 is leaving fuel in tanks

### ISSUE THREAD

**Issue by t0chas** [BrettWebb/KerbalSmartParts#15]
Hi I just downloaded version v1.6.6

and the fuel sensor is leaving tanks with a bit of fuel (about 20m/s worth of it)

![2015-07-06_00001](https://cloud.githubusercontent.com/assets/4617293/8537905/95bd2c32-242a-11e5-91da-cffe54bf8ed5.jpg)
![2015-07-06_00002](https://cloud.githubusercontent.com/assets/4617293/8537906/984b916e-242a-11e5-84fa-a0a6ce111a30.jpg)

**Comment by BrettWebb** [comment]
Thanks for the report. 

The fuel sensor actually will fire above 0% under a specific set of conditions. One, the current percentage has to be at or less than 1% of total capacity for the monitored resource, and two, the resource in question is no longer being drained (for example, by an active engine).

This was done to allow for floating point errors, since some engines won't drain a tank completely, and so the 0% condition would never actually trigger.

In your example, the remaining fuel is 0.3 percent of total capacity. That is to say, it is about a third of a percent. If your engine stopped firing, for any reason, at that level, it would activate the auto stager.

Assuming the engine was active, was that stage still under thrust when it jettisoned? I just tried to replicate it with a skipper/jumbo fuel tank and it was able to drain to 0%. Do you have any mods that adjust engine fuel consumption/ISP/thrust?

**Comment by t0chas** [comment]
Hi, 

No I dont have any mods that change engines or isp.

but I do use RemoteTech, the sensor fired right after the RemoteTech autopilot finished a burn.
It does match your explanation (below 1% and no active engines)
